### ISSUE TITLE
文字を入力する度に「No found」の通知が出るので、オプションなどで「No found」の場合は表示させない設定を追加して欲しい

### ISSUE THREAD

**Issue by tegnike** [ktyubeshi/mojibake-inspector#1]
![CleanShot 2024-12-16 at 09 23 10](https://github.com/user-attachments/assets/b78fd96b-a726-48b0-a81a-ecc5dcb49b5c)

**Comment by ktyubeshi** [comment]
フィードバックありがとうございます!
デフォルト無効で設定機能を追加しようと思います。

**Comment by ktyubeshi** [comment]
設定機能を追加したバージョンを dev/0.0.16 としてReleaseに追加しました。
ご確認ください。
https://github.com/ktyubeshi/mojibake-inspector/releases/tag/dev%2F0.0.16

**Comment by tegnike** [comment]
表示されないことを確認できました！
ご対応ありがとうございます！
